### ISSUE TITLE
Features wishlist

### ISSUE THREAD

**Issue by ryukinix** [xi-frontend/xim#3]
## Description

This issue handles what should be implemented into xim.

## Roadmap

- [ ] Key bindings
   - [x] (^s) Save
   - [x] (^q) Quit
   - [ ] (^x) Cut
   - [ ] (^c) Copy
   - [ ] (^v) Paste
   - [ ] (^f) Filter
   - [ ] (^d) Multiple cursor
   - [ ] (^:) Command prompt
- [ ] Status bar
   - [ ] Name of current file
   - [ ] File type/extension
   - [ ] File size and metrics
- [ ] Custom theme support
- [ ] Multiple cursor support
- [ ] External copy/paste (x and wayland support)
- [ ] Command Prompt
- [ ] Line numbers
- [ ] Gutter

**Comment by ryukinix** [comment]
This issue was moved to xi-frontend/xim-#8
