### ISSUE TITLE
Features wishlist

### ISSUE THREAD

**Issue by ryukinix** [xi-frontend/xim#8]
_From @ryukinix on January 31, 2018 23:3_

## Description

This issue handles what should be implemented into xim.

## Roadmap

- [ ] Key bindings
   - [x] (^s) Save
   - [x] (^q) Quit
   - [ ] (^x) Cut
   - [ ] (^c) Copy
   - [ ] (^v) Paste
   - [ ] (^f) Filter
   - [ ] (^d) Multiple cursor
   - [ ] (^:) Command prompt
- [ ] Status bar
   - [ ] Name of current file
   - [ ] File type/extension
   - [ ] File size and metrics
- [ ] Custom theme support
- [ ] Multiple cursor support
- [ ] External copy/paste (x and wayland support)
- [ ] Command Prompt
- [ ] Line numbers
- [ ] Gutter

_Copied from original issue: xi-frontend/xim#3_

**Comment by ryukinix** [comment]
[xim.pdf](https://github.com/xi-frontend/xim/files/1784000/xim.pdf)

**Comment by cmyr** [comment]
Want to chime in that at least some of the statusbar stuff should probably be provided by core; I've been thinking about that for a while for xi-mac. If you get to that point and more getting more info from core would be useful, open an issue in the xi-editor repo.

**Comment by ryukinix** [comment]
Thanks for the attention in the project @cmyr! I think that makes sense handle status stuff as interface of xi-core, since statusbar is something desired basically for all frontend editors.

I'll open a new issue when we have more solid design of xim to share thoughts.
